rm "color_image_track_lines.png"
rm "fluorescence_image_track_lines.png"
rm "control_knob.png"
rm "display_options_setting.png"
rm "2 microscope configurations.png"
rm "Basic Stereo-seq image processing logic.png"
rm "Bin N MID filter1.png"
rm "Bin N MID filter2.png"
rm "Bin N boundaries1.png"
rm "Bin N boundaries2.png"
rm "Bin N boundaries3.png"
rm "Bin N cluster opacity1.png"
rm "Bin N cluster opacity2.png"
rm "Bin N color bar1.png"
rm "Bin N color bar2.png"
rm "Bin N color1.png"
rm "Bin N color2.png"
rm "Bin N display schemes1.png"
rm "Bin N display schemes2.png"
rm "Bin N heatmap opacity1.png"
rm "Bin N heatmap opacity2.png"
rm "Bin N spot size1.png"
rm "Bin N spot size2.png"
rm "Cell Bin Form of cells & Outline color1.png"
rm "Cell Bin Form of cells & Outline color2.png"
rm "Cell Bin Form of cells & Outline color3.png"
rm "Cell Bin cluster opacity1.png"
rm "Cell Bin cluster opacity2.png"
rm "Cell Bin color bar1.png"
rm "Cell Bin color bar2.png"
rm "Cell Bin color1.png"
rm "Cell Bin color2.png"
rm "Cell Bin heatmap opacity1.png"
rm "Cell Bin heatmap opacity2.png"
rm "HE-input czi.png"
rm "HE-input tar.png"
rm "HE-input tif.png"
rm "HE-input tiles-STOmicsGoOptical.png"
rm "HE-input tiles-motic.png"
rm "IP step1.png"
rm "Reference template w image.png"
rm "Reference template.png"
rm "Screenshot download.png"
rm "add microscope configuration.png"
rm "check alignment stitching issue.png"
rm "check alignment.png"
rm "color-export directory.png"
rm "color-export.png"
rm "color-image parsing info.png"
rm "color-select image file.png"
rm "color-trackline overlap example.png"
rm "create a new group.png"
rm "create a new label to an exist group.png"
rm "custom group with 2 labels.png"
rm "download file.png"
rm "grayscale-export directory.png"
rm "grayscale-export.png"
rm "grayscale-image parsing info.png"
rm "grayscale-select image file.png"
rm "grayscale-trackline overlap example.png"
rm "group more.png"
rm "group optimization1.png"
rm "group optimization2.png"
rm "image QC interface microscope info.png"
rm "image QC interface.png"
rm "image QC pass.png"
rm "image calibration.png"
rm "image clarity.png"
rm "interface navigation-Bin Sizes.png"
rm "interface navigation-analysis layer.png"
rm "interface navigation-canvas.png"
rm "interface navigation-feature menu.png"
rm "interface navigation-group menu.png"
rm "interface navigation-image layer.png"
rm "interface navigation.png"
rm "label more.png"
rm "microscope config IP.png"
rm "microscope settings-add_edit.png"
rm "mif-input czi.png"
rm "mif-input czis.png"
rm "mif-input tar.png"
rm "mif-input tif.png"
rm "mif-input tiles-STOmicsGoOptical.png"
rm "mif-input tiles-motic.png"
rm "multi-grayscale-export directory.png"
rm "multi-grayscale-image parsing info.png"
rm "nuclei-input czi.png"
rm "nuclei-input tar.png"
rm "nuclei-input tif.png"
rm "nuclei-input tiles-leica.png"
rm "nuclei-input tiles-motic.png"
rm "search_feature.png"
rm "select dataset-open.png"
rm "setting-general-autoupdate.png"
rm "show label bin N.png"
rm "show label cellbin.png"
rm "stitching evaluation.png"
rm "tif uploading IP.png"
rm "trackline detection.png"
rm "Contrast.png"
rm "Flip.png"
rm "MID filter saving directory.png"
rm "MID filter saving.png"
rm "Rotation.png"
rm "Step move.png"
rm "add regions done.png"
rm "add regions for a label select group name.png"
rm "add regions for a label select label name.png"
rm "add regions for a label.png"
rm "adjust MID filter.png"
rm "adjust opacity HE.png"
rm "adjust opacity.png"
rm "brightness.png"
rm "change color.png"
rm "change color_canvas.png"
rm "co-expressed_merge.png"
rm "co-expressed_violet.png"
rm "co-expressed_yellow.png"
rm "differential expression export-cluster options.png"
rm "differential expression export-cluster.png"
rm "differential expression export-group options.png"
rm "differential expression export-group.png"
rm "differential expression load result.png"
rm "differential expression saving directory.png"
rm "differential expression select feature and show as multi-colored.png"
rm "differential expression select feature.png"
rm "differential expression show table.png"
rm "eraser.png"
rm "export lasso geojson directory.png"
rm "export lasso geojson.png"
rm "export.png"
rm "image QC output.png"
rm "labeled region1.png"
rm "labeled region2.png"
rm "lasso cluster region that have bacteria.png"
rm "lasso label and group.png"
rm "lasso region1.png"
rm "lasso region2.png"
rm "lasso region3.png"
rm "lasso region4.png"
rm "lasso region5.png"
rm "lasso.png"
rm "micro-host side-by-side.png"
rm "normalization.png"
rm "not co-expressed.png"
rm "not co-expressed_canvas.png"
rm "opacity.png"
rm "open micro layer in new window.png"
rm "pencil.png"
rm "qc upload custom a new cloud and save.png"
rm "saturation.png"
rm "scale.png"
rm "select cluster.png"
rm "show in multicolor.png"
rm "summarized heatmap.png"
rm "color-add or replace matrix.png"
rm "color-cell mask brush.png"
rm "color-cell mask eraser.png"
rm "color-cell mask import result.png"
rm "color-cell mask import.png"
rm "color-cell mask lasso deselect.png"
rm "color-cell mask lasso.png"
rm "color-cell mask replace.png"
rm "color-cell mask tag.png"
rm "color-cell seg zoom.png"
rm "color-cell seg.png"
rm "color-chip tracklines.png"
rm "color-regiatration.png"
rm "color-tissue mask brush.png"
rm "color-tissue mask eraser.png"
rm "color-tissue mask import result.png"
rm "color-tissue mask import.png"
rm "color-tissue mask lasso.png"
rm "color-tissue mask replace.png"
rm "color-tissue mask tag.png"
rm "color-tissue seg.png"
rm "grayscale-add or replace matrix.png"
rm "grayscale-cell mask brush.png"
rm "grayscale-cell mask eraser.png"
rm "grayscale-cell mask import result.png"
rm "grayscale-cell mask import.png"
rm "grayscale-cell mask lasso deselect.png"
rm "grayscale-cell mask lasso.png"
rm "grayscale-cell mask replace.png"
rm "grayscale-cell mask tag.png"
rm "grayscale-cell seg zoom.png"
rm "grayscale-cell seg.png"
rm "grayscale-chip tracklines.png"
rm "grayscale-regiatration.png"
rm "grayscale-tissue mask brush.png"
rm "grayscale-tissue mask eraser.png"
rm "grayscale-tissue mask import result.png"
rm "grayscale-tissue mask import.png"
rm "grayscale-tissue mask lasso.png"
rm "grayscale-tissue mask replace.png"
rm "grayscale-tissue mask tag.png"
rm "grayscale-tissue seg.png"
rm "multi-grayscale-IF threshold adjust after.png"
rm "multi-grayscale-IF threshold adjust before.png"
rm "multi-grayscale-IF threshold.png"
rm "multi-grayscale-add or replace matrix.png"
rm "multi-grayscale-cell mask brush.png"
rm "multi-grayscale-cell mask eraser.png"
rm "multi-grayscale-cell mask import result.png"
rm "multi-grayscale-cell mask import.png"
rm "multi-grayscale-cell mask lasso deselect.png"
rm "multi-grayscale-cell mask lasso.png"
rm "multi-grayscale-cell mask replace.png"
rm "multi-grayscale-cell mask tag.png"
rm "multi-grayscale-cell seg zoom.png"
rm "multi-grayscale-cell seg.png"
rm "multi-grayscale-chip tracklines.png"
rm "multi-grayscale-color and morphology.png"
rm "multi-grayscale-export.png"
rm "multi-grayscale-regiatration.png"
rm "multi-grayscale-tissue mask brush.png"
rm "multi-grayscale-tissue mask eraser.png"
rm "multi-grayscale-tissue mask import result.png"
rm "multi-grayscale-tissue mask import.png"
rm "multi-grayscale-tissue mask lasso.png"
rm "multi-grayscale-tissue mask replace.png"
rm "multi-grayscale-tissue mask tag.png"
rm "multi-grayscale-tissue seg.png"
rm "1710909926805.png"
